# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eaf6eee99c535e212e1a649e9d92912f04b5b59cbcd8fe3a4666e5ee6230195c7a79d1018ef0eaefbbc41947981f172ad6cf1dfb6979e57b7a6a9694bd039979

test:
  secret_key_base: b59d59d2e3ae4705613c4782552ff5eba42fc20663b98ffeb4087670a48cf15f84158a3e1b4656ec04bcdb2c6e13beac609e33596afa7f0f40a4839b37b9b608

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
